CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role ENUM('helper', 'admin') DEFAULT 'helper',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE products (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description TEXT,
    price FLOAT NOT NULL,
    stock INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE orders (
    id INT AUTO_INCREMENT PRIMARY KEY,
    user_id INT NOT NULL,
    total DECIMAL(10, 2) NOT NULL,
    customer_name VARCHAR(100) NOT NULL,
    customer_phone VARCHAR(15),
    customer_address TEXT,
    status ENUM('pending', 'done') DEFAULT 'pending',
    expired_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE order_items (
    id INT AUTO_INCREMENT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    subtotal DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
    FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);


INSERT INTO products (name, description, price, stock) VALUES
('Men\'s Casual Shirt', 'Lightweight casual shirt perfect for everyday wear.', 524850, 120),
('Women\'s Maxi Dress', 'Elegant maxi dress for special occasions.', 899850, 50),
('Cargo Shorts', 'Durable cargo shorts with multiple pockets.', 449850, 100),
('Pullover Sweater', 'Cozy pullover sweater for chilly evenings.', 599850, 80),
('Men\'s Suit', 'Tailored suit for formal events and business meetings.', 4499850, 20),
('Women\'s Cardigan', 'Soft cardigan for layering over outfits.', 524850, 90),
('Athletic Shorts', 'Breathable athletic shorts for workouts.', 374850, 150),
('Graphic Tank Top', 'Trendy tank top with a fun graphic design.', 299850, 200),
('Men\'s Dress Pants', 'Classic dress pants for formal occasions.', 749850, 60),
('Women\'s Jumpsuit', 'Stylish jumpsuit for a chic and modern look.', 1049850, 40),
('Fleece Hoodie', 'Warm fleece hoodie for outdoor activities.', 749850, 70),
('Men\'s Pajama Pants', 'Comfortable pajama pants for a good night\'s sleep.', 449850, 100),
('Women\'s Leggings', 'High-quality leggings for workouts and casual wear.', 449850, 150),
('Men\'s Windbreaker', 'Lightweight windbreaker for unpredictable weather.', 899850, 50),
('Women\'s Tunic', 'Flowy tunic top for a relaxed fit.', 524850, 80),
('Men\'s Beanie', 'Warm beanie hat for cold weather.', 239850, 120),
('Women\'s Scarf', 'Stylish scarf to accessorize any outfit.', 299850, 100),
('Men\'s Flip Flops', 'Comfortable flip flops for the beach.', 224850, 200),
('Women\'s Heels', 'Elegant heels for formal occasions.', 1199850, 30),
('Men\'s Sneakers', 'Trendy sneakers for everyday wear.', 899850, 60),
('Women\'s Sandals', 'Comfortable sandals for summer outings.', 449850, 70),
('Men\'s Dress Shirt', 'Classic dress shirt for business and formal wear.', 599850, 80),
('Women\'s Activewear', 'Stylish activewear set for workouts.', 749850, 50),
('Men\'s Cargo Pants', 'Functional cargo pants for outdoor adventures.', 749850, 60),
('Women\'s Blazer', 'Tailored blazer for a professional look.', 1349850, 40),
('Men\'s Sports Jacket', 'Casual sports jacket for a smart-casual look.', 1199850, 50),
('Women\'s Chinos', 'Comfortable chinos for a polished appearance.', 599850, 70),
('Men\'s Running Shorts', 'Lightweight running shorts for maximum comfort.', 374850, 150),
('Women\'s Sports Bra', 'Supportive sports bra for active lifestyles.', 449850, 90),
('Men\'s Casual Sneakers', 'Stylish casual sneakers for everyday use.', 899850, 60),
('Women\'s Midi Skirt', 'Chic midi skirt for versatile styling.', 599850, 80),
('Men\'s Long Sleeve Shirt', 'Classic long sleeve shirt for layering.', 524850, 100),
('Women\'s Off-Shoulder Top', 'Trendy off-shoulder top for a stylish look.', 449850, 70),
('Men\'s Swim Shorts', 'Quick-dry swim shorts for beach activities.', 374850, 150),
('Women\'s Romper', 'Cute romper for summer outings.', 599850, 50),
('Men\'s Casual Jacket', 'Lightweight casual jacket for layering.', 899850, 40),
('Women\'s Palazzo Pants', 'Flowy palazzo pants for a comfortable fit.', 749850, 60),
('Men\'s Thermal Shirt', 'Warm thermal shirt for cold weather.', 449850, 80),
('Women\'s Kimono', 'Lightweight kimono for layering over outfits.', 524850, 90),
('Men\'s Dress Boots', 'Stylish dress boots for formal occasions.', 1349850, 30),
('Women\'s Ankle Boots', 'Chic ankle boots for a fashionable look.', 1199850, 50),
('Men\'s Casual Trousers', 'Comfortable trousers for everyday wear.', 749850, 60),
('Women\'s Sweater Dress', 'Cozy sweater dress for a stylish winter look.', 899850, 40),
('Men\'s Graphic Sweatshirt', 'Trendy sweatshirt with a unique graphic design.', 599850, 70),
('Women\'s High-Waisted Jeans', 'Stylish high-waisted jeans for a flattering fit.', 749850, 80),
('Men\'s Cargo Vest', 'Functional cargo vest for outdoor activities.', 524850, 100),
('Women\'s Cropped Top', 'Trendy cropped top for a casual look.', 374850, 150),
('Men\'s Sports Shorts', 'Comfortable sports shorts for workouts.', 449850, 90),
('Women\'s Maxi Skirt', 'Flowy maxi skirt for a bohemian vibe.', 599850, 60),
('Men\'s Casual Blazer', 'Smart casual blazer for versatile styling.', 1349850, 40),
('Women\'s Wrap Dress', 'Elegant wrap dress for a flattering silhouette.', 899850, 50),
('Men\'s Fleece Vest', 'Warm fleece vest for layering in winter.', 599850, 70),
('Women\'s Tulle Skirt', 'Fun tulle skirt for special occasions.', 749850, 30),
('Men\'s Casual Loafers', 'Stylish loafers for a smart-casual look.', 1199850, 50),
('Women\'s Espadrilles', 'Comfortable espadrilles for summer wear.', 524850, 90),
('Men\'s Henley Shirt', 'Classic henley shirt for a relaxed fit.', 449850, 100),
('Women\'s Peplum Top', 'Flattering peplum top for a stylish look.', 599850, 80),
('Men\'s Chino Shorts', 'Versatile chino shorts for summer outings.', 449850, 150),
('Women\'s Slip-On Sneakers', 'Easy-to-wear slip-on sneakers for casual days.', 749850, 60),
('Men\'s Puffer Jacket', 'Warm puffer jacket for cold weather.', 1499850, 40),
('Women\'s Quilted Jacket', 'Stylish quilted jacket for a chic look.', 1349850, 50),
('Men\'s Dressy Casual Shirt', 'Smart casual shirt for versatile styling.', 599850, 70),
('Women\'s Lace Top', 'Elegant lace top for special occasions.', 749850, 30),
('Men\'s Utility Jacket', 'Functional utility jacket for outdoor adventures.', 1199850, 50),
('Women\'s Ripped Jeans', 'Trendy ripped jeans for a casual look.', 749850, 60),
('Men\'s Casual Slip-Ons', 'Comfortable slip-on shoes for everyday wear.', 899850, 40),
('Women\'s Flannel Shirt', 'Cozy flannel shirt for a relaxed fit.', 524850, 90),
('Men\'s Performance T-Shirt', 'High-performance t-shirt for workouts.', 449850, 100),
('Women\'s Active Leggings', 'Stylish active leggings for workouts.', 599850, 80),
('Men\'s Casual Backpack', 'Durable backpack for everyday use.', 749850, 60),
('Women\'s Crossbody Bag', 'Chic crossbody bag for hands-free convenience.', 524850, 90),
('Men\'s Casual Watch', 'Stylish watch for everyday wear.', 1349850, 40),
('Women\'s Statement Earrings', 'Trendy earrings to complete your outfit.', 299850, 100),
('Men\'s Beaded Bracelet', 'Stylish beaded bracelet for a casual look.', 224850, 150),
('Women\'s Hair Accessories', 'Fashionable hair accessories for any occasion.', 149850, 200),
('Men\'s Sunglasses', 'Stylish sunglasses for sun protection.', 449850, 100),
('Women\'s Tote Bag', 'Spacious tote bag for everyday use.', 599850, 60),
('Men\'s Casual Belt', 'Stylish casual belt for everyday wear.', 374850, 80),
('Women\'s Clutch Bag', 'Elegant clutch bag for formal occasions.', 749850, 30);